// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.CommunityPersonDataOnDemand;
import com.reltecsoft.lookon.domain.CommunityPersonIntegrationTest;
import com.reltecsoft.lookon.domain.CommunityPersonPK;
import com.reltecsoft.lookon.repository.CommunityPersonRepository;
import com.reltecsoft.lookon.service.CommunityPersonService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CommunityPersonIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CommunityPersonIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CommunityPersonIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CommunityPersonIntegrationTest: @Transactional;
    
    @Autowired
    CommunityPersonDataOnDemand CommunityPersonIntegrationTest.dod;
    
    @Autowired
    CommunityPersonService CommunityPersonIntegrationTest.communityPersonService;
    
    @Autowired
    CommunityPersonRepository CommunityPersonIntegrationTest.communityPersonRepository;
    
    @Test
    public void CommunityPersonIntegrationTest.testCountAllCommunitypeople() {
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to initialize correctly", dod.getRandomCommunityPerson());
        long count = communityPersonService.countAllCommunitypeople();
        Assert.assertTrue("Counter for 'CommunityPerson' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CommunityPersonIntegrationTest.testFindCommunityPerson() {
        CommunityPerson obj = dod.getRandomCommunityPerson();
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to initialize correctly", obj);
        CommunityPersonPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to provide an identifier", id);
        obj = communityPersonService.findCommunityPerson(id);
        Assert.assertNotNull("Find method for 'CommunityPerson' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CommunityPerson' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CommunityPersonIntegrationTest.testFindAllCommunitypeople() {
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to initialize correctly", dod.getRandomCommunityPerson());
        long count = communityPersonService.countAllCommunitypeople();
        Assert.assertTrue("Too expensive to perform a find all test for 'CommunityPerson', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CommunityPerson> result = communityPersonService.findAllCommunitypeople();
        Assert.assertNotNull("Find all method for 'CommunityPerson' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CommunityPerson' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CommunityPersonIntegrationTest.testFindCommunityPersonEntries() {
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to initialize correctly", dod.getRandomCommunityPerson());
        long count = communityPersonService.countAllCommunitypeople();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CommunityPerson> result = communityPersonService.findCommunityPersonEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CommunityPerson' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CommunityPerson' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CommunityPersonIntegrationTest.testSaveCommunityPerson() {
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to initialize correctly", dod.getRandomCommunityPerson());
        CommunityPerson obj = dod.getNewTransientCommunityPerson(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to provide a new transient entity", obj);
        try {
            communityPersonService.saveCommunityPerson(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        communityPersonRepository.flush();
        Assert.assertNotNull("Expected 'CommunityPerson' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CommunityPersonIntegrationTest.testDeleteCommunityPerson() {
        CommunityPerson obj = dod.getRandomCommunityPerson();
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to initialize correctly", obj);
        CommunityPersonPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CommunityPerson' failed to provide an identifier", id);
        obj = communityPersonService.findCommunityPerson(id);
        communityPersonService.deleteCommunityPerson(obj);
        communityPersonRepository.flush();
        Assert.assertNull("Failed to remove 'CommunityPerson' with identifier '" + id + "'", communityPersonService.findCommunityPerson(id));
    }
    
}
