// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.CompanyStatusDataOnDemand;
import com.reltecsoft.lookon.domain.CompanyStatusIntegrationTest;
import com.reltecsoft.lookon.repository.CompanyStatusRepository;
import com.reltecsoft.lookon.service.CompanyStatusService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CompanyStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CompanyStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CompanyStatusIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CompanyStatusIntegrationTest: @Transactional;
    
    @Autowired
    CompanyStatusDataOnDemand CompanyStatusIntegrationTest.dod;
    
    @Autowired
    CompanyStatusService CompanyStatusIntegrationTest.companyStatusService;
    
    @Autowired
    CompanyStatusRepository CompanyStatusIntegrationTest.companyStatusRepository;
    
    @Test
    public void CompanyStatusIntegrationTest.testCountAllCompanyStatuses() {
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to initialize correctly", dod.getRandomCompanyStatus());
        long count = companyStatusService.countAllCompanyStatuses();
        Assert.assertTrue("Counter for 'CompanyStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CompanyStatusIntegrationTest.testFindCompanyStatus() {
        CompanyStatus obj = dod.getRandomCompanyStatus();
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to provide an identifier", id);
        obj = companyStatusService.findCompanyStatus(id);
        Assert.assertNotNull("Find method for 'CompanyStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CompanyStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CompanyStatusIntegrationTest.testFindAllCompanyStatuses() {
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to initialize correctly", dod.getRandomCompanyStatus());
        long count = companyStatusService.countAllCompanyStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'CompanyStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CompanyStatus> result = companyStatusService.findAllCompanyStatuses();
        Assert.assertNotNull("Find all method for 'CompanyStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CompanyStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CompanyStatusIntegrationTest.testFindCompanyStatusEntries() {
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to initialize correctly", dod.getRandomCompanyStatus());
        long count = companyStatusService.countAllCompanyStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CompanyStatus> result = companyStatusService.findCompanyStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CompanyStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CompanyStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CompanyStatusIntegrationTest.testFlush() {
        CompanyStatus obj = dod.getRandomCompanyStatus();
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to provide an identifier", id);
        obj = companyStatusService.findCompanyStatus(id);
        Assert.assertNotNull("Find method for 'CompanyStatus' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCompanyStatus(obj);
        Integer currentVersion = obj.getVersion();
        companyStatusRepository.flush();
        Assert.assertTrue("Version for 'CompanyStatus' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompanyStatusIntegrationTest.testUpdateCompanyStatusUpdate() {
        CompanyStatus obj = dod.getRandomCompanyStatus();
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to provide an identifier", id);
        obj = companyStatusService.findCompanyStatus(id);
        boolean modified =  dod.modifyCompanyStatus(obj);
        Integer currentVersion = obj.getVersion();
        CompanyStatus merged = companyStatusService.updateCompanyStatus(obj);
        companyStatusRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CompanyStatus' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompanyStatusIntegrationTest.testSaveCompanyStatus() {
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to initialize correctly", dod.getRandomCompanyStatus());
        CompanyStatus obj = dod.getNewTransientCompanyStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CompanyStatus' identifier to be null", obj.getId());
        try {
            companyStatusService.saveCompanyStatus(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        companyStatusRepository.flush();
        Assert.assertNotNull("Expected 'CompanyStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CompanyStatusIntegrationTest.testDeleteCompanyStatus() {
        CompanyStatus obj = dod.getRandomCompanyStatus();
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CompanyStatus' failed to provide an identifier", id);
        obj = companyStatusService.findCompanyStatus(id);
        companyStatusService.deleteCompanyStatus(obj);
        companyStatusRepository.flush();
        Assert.assertNull("Failed to remove 'CompanyStatus' with identifier '" + id + "'", companyStatusService.findCompanyStatus(id));
    }
    
}
