// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.CompanyStatus;
import com.reltecsoft.lookon.domain.CompanyStatusDataOnDemand;
import com.reltecsoft.lookon.repository.CompanyStatusRepository;
import com.reltecsoft.lookon.service.CompanyStatusService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CompanyStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CompanyStatusDataOnDemand: @Component;
    
    private Random CompanyStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<CompanyStatus> CompanyStatusDataOnDemand.data;
    
    @Autowired
    CompanyStatusService CompanyStatusDataOnDemand.companyStatusService;
    
    @Autowired
    CompanyStatusRepository CompanyStatusDataOnDemand.companyStatusRepository;
    
    public CompanyStatus CompanyStatusDataOnDemand.getNewTransientCompanyStatus(int index) {
        CompanyStatus obj = new CompanyStatus();
        setName(obj, index);
        return obj;
    }
    
    public void CompanyStatusDataOnDemand.setName(CompanyStatus obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = new Random().nextInt(10) + name.substring(1, 20);
        }
        obj.setName(name);
    }
    
    public CompanyStatus CompanyStatusDataOnDemand.getSpecificCompanyStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CompanyStatus obj = data.get(index);
        Long id = obj.getId();
        return companyStatusService.findCompanyStatus(id);
    }
    
    public CompanyStatus CompanyStatusDataOnDemand.getRandomCompanyStatus() {
        init();
        CompanyStatus obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return companyStatusService.findCompanyStatus(id);
    }
    
    public boolean CompanyStatusDataOnDemand.modifyCompanyStatus(CompanyStatus obj) {
        return false;
    }
    
    public void CompanyStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = companyStatusService.findCompanyStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CompanyStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CompanyStatus>();
        for (int i = 0; i < 10; i++) {
            CompanyStatus obj = getNewTransientCompanyStatus(i);
            try {
                companyStatusService.saveCompanyStatus(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            companyStatusRepository.flush();
            data.add(obj);
        }
    }
    
}
