// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtChatStatusDataOnDemand;
import com.reltecsoft.lookon.domain.DtChatStatusIntegrationTest;
import com.reltecsoft.lookon.repository.ChatStatusRepository;
import com.reltecsoft.lookon.service.ChatStatusService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DtChatStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DtChatStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DtChatStatusIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DtChatStatusIntegrationTest: @Transactional;
    
    @Autowired
    DtChatStatusDataOnDemand DtChatStatusIntegrationTest.dod;
    
    @Autowired
    ChatStatusService DtChatStatusIntegrationTest.chatStatusService;
    
    @Autowired
    ChatStatusRepository DtChatStatusIntegrationTest.chatStatusRepository;
    
    @Test
    public void DtChatStatusIntegrationTest.testCountAllDtChatStatuses() {
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to initialize correctly", dod.getRandomDtChatStatus());
        long count = chatStatusService.countAllDtChatStatuses();
        Assert.assertTrue("Counter for 'DtChatStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DtChatStatusIntegrationTest.testFindDtChatStatus() {
        DtChatStatus obj = dod.getRandomDtChatStatus();
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to provide an identifier", id);
        obj = chatStatusService.findDtChatStatus(id);
        Assert.assertNotNull("Find method for 'DtChatStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DtChatStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DtChatStatusIntegrationTest.testFindAllDtChatStatuses() {
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to initialize correctly", dod.getRandomDtChatStatus());
        long count = chatStatusService.countAllDtChatStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'DtChatStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DtChatStatus> result = chatStatusService.findAllDtChatStatuses();
        Assert.assertNotNull("Find all method for 'DtChatStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DtChatStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DtChatStatusIntegrationTest.testFindDtChatStatusEntries() {
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to initialize correctly", dod.getRandomDtChatStatus());
        long count = chatStatusService.countAllDtChatStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DtChatStatus> result = chatStatusService.findDtChatStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DtChatStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DtChatStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DtChatStatusIntegrationTest.testSaveDtChatStatus() {
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to initialize correctly", dod.getRandomDtChatStatus());
        DtChatStatus obj = dod.getNewTransientDtChatStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DtChatStatus' identifier to be null", obj.getId());
        try {
            chatStatusService.saveDtChatStatus(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        chatStatusRepository.flush();
        Assert.assertNotNull("Expected 'DtChatStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DtChatStatusIntegrationTest.testDeleteDtChatStatus() {
        DtChatStatus obj = dod.getRandomDtChatStatus();
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtChatStatus' failed to provide an identifier", id);
        obj = chatStatusService.findDtChatStatus(id);
        chatStatusService.deleteDtChatStatus(obj);
        chatStatusRepository.flush();
        Assert.assertNull("Failed to remove 'DtChatStatus' with identifier '" + id + "'", chatStatusService.findDtChatStatus(id));
    }
    
}
