// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtChatRoleDataOnDemand;
import com.reltecsoft.lookon.domain.DtChatRoleIntegrationTest;
import com.reltecsoft.lookon.repository.ChatRoleRepository;
import com.reltecsoft.lookon.service.ChatRole;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DtChatRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DtChatRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DtChatRoleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DtChatRoleIntegrationTest: @Transactional;
    
    @Autowired
    DtChatRoleDataOnDemand DtChatRoleIntegrationTest.dod;
    
    @Autowired
    ChatRole DtChatRoleIntegrationTest.chatRole;
    
    @Autowired
    ChatRoleRepository DtChatRoleIntegrationTest.chatRoleRepository;
    
    @Test
    public void DtChatRoleIntegrationTest.testCountAllDtChatRoles() {
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to initialize correctly", dod.getRandomDtChatRole());
        long count = chatRole.countAllDtChatRoles();
        Assert.assertTrue("Counter for 'DtChatRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DtChatRoleIntegrationTest.testFindDtChatRole() {
        DtChatRole obj = dod.getRandomDtChatRole();
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to provide an identifier", id);
        obj = chatRole.findDtChatRole(id);
        Assert.assertNotNull("Find method for 'DtChatRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DtChatRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DtChatRoleIntegrationTest.testFindAllDtChatRoles() {
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to initialize correctly", dod.getRandomDtChatRole());
        long count = chatRole.countAllDtChatRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'DtChatRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DtChatRole> result = chatRole.findAllDtChatRoles();
        Assert.assertNotNull("Find all method for 'DtChatRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DtChatRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DtChatRoleIntegrationTest.testFindDtChatRoleEntries() {
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to initialize correctly", dod.getRandomDtChatRole());
        long count = chatRole.countAllDtChatRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DtChatRole> result = chatRole.findDtChatRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DtChatRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DtChatRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DtChatRoleIntegrationTest.testSaveDtChatRole() {
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to initialize correctly", dod.getRandomDtChatRole());
        DtChatRole obj = dod.getNewTransientDtChatRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DtChatRole' identifier to be null", obj.getId());
        try {
            chatRole.saveDtChatRole(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        chatRoleRepository.flush();
        Assert.assertNotNull("Expected 'DtChatRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DtChatRoleIntegrationTest.testDeleteDtChatRole() {
        DtChatRole obj = dod.getRandomDtChatRole();
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtChatRole' failed to provide an identifier", id);
        obj = chatRole.findDtChatRole(id);
        chatRole.deleteDtChatRole(obj);
        chatRoleRepository.flush();
        Assert.assertNull("Failed to remove 'DtChatRole' with identifier '" + id + "'", chatRole.findDtChatRole(id));
    }
    
}
