// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtCompanyStatus;
import com.reltecsoft.lookon.domain.DtCompanyStatusDataOnDemand;
import com.reltecsoft.lookon.repository.CompanyStatusRepository;
import com.reltecsoft.lookon.service.CompanyStatusService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DtCompanyStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DtCompanyStatusDataOnDemand: @Component;
    
    private Random DtCompanyStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<DtCompanyStatus> DtCompanyStatusDataOnDemand.data;
    
    @Autowired
    CompanyStatusService DtCompanyStatusDataOnDemand.companyStatusService;
    
    @Autowired
    CompanyStatusRepository DtCompanyStatusDataOnDemand.companyStatusRepository;
    
    public DtCompanyStatus DtCompanyStatusDataOnDemand.getNewTransientDtCompanyStatus(int index) {
        DtCompanyStatus obj = new DtCompanyStatus();
        setName(obj, index);
        return obj;
    }
    
    public void DtCompanyStatusDataOnDemand.setName(DtCompanyStatus obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public DtCompanyStatus DtCompanyStatusDataOnDemand.getSpecificDtCompanyStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DtCompanyStatus obj = data.get(index);
        Integer id = obj.getId();
        return companyStatusService.findDtCompanyStatus(id);
    }
    
    public DtCompanyStatus DtCompanyStatusDataOnDemand.getRandomDtCompanyStatus() {
        init();
        DtCompanyStatus obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return companyStatusService.findDtCompanyStatus(id);
    }
    
    public boolean DtCompanyStatusDataOnDemand.modifyDtCompanyStatus(DtCompanyStatus obj) {
        return false;
    }
    
    public void DtCompanyStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = companyStatusService.findDtCompanyStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DtCompanyStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DtCompanyStatus>();
        for (int i = 0; i < 10; i++) {
            DtCompanyStatus obj = getNewTransientDtCompanyStatus(i);
            try {
                companyStatusService.saveDtCompanyStatus(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            companyStatusRepository.flush();
            data.add(obj);
        }
    }
    
}
