// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtCommentStatus;
import com.reltecsoft.lookon.domain.DtCommentStatusDataOnDemand;
import com.reltecsoft.lookon.repository.CommentStatusRepository;
import com.reltecsoft.lookon.service.CommentStatusService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DtCommentStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DtCommentStatusDataOnDemand: @Component;
    
    private Random DtCommentStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<DtCommentStatus> DtCommentStatusDataOnDemand.data;
    
    @Autowired
    CommentStatusService DtCommentStatusDataOnDemand.commentStatusService;
    
    @Autowired
    CommentStatusRepository DtCommentStatusDataOnDemand.commentStatusRepository;
    
    public DtCommentStatus DtCommentStatusDataOnDemand.getNewTransientDtCommentStatus(int index) {
        DtCommentStatus obj = new DtCommentStatus();
        setName(obj, index);
        return obj;
    }
    
    public void DtCommentStatusDataOnDemand.setName(DtCommentStatus obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public DtCommentStatus DtCommentStatusDataOnDemand.getSpecificDtCommentStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DtCommentStatus obj = data.get(index);
        Integer id = obj.getId();
        return commentStatusService.findDtCommentStatus(id);
    }
    
    public DtCommentStatus DtCommentStatusDataOnDemand.getRandomDtCommentStatus() {
        init();
        DtCommentStatus obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return commentStatusService.findDtCommentStatus(id);
    }
    
    public boolean DtCommentStatusDataOnDemand.modifyDtCommentStatus(DtCommentStatus obj) {
        return false;
    }
    
    public void DtCommentStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = commentStatusService.findDtCommentStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DtCommentStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DtCommentStatus>();
        for (int i = 0; i < 10; i++) {
            DtCommentStatus obj = getNewTransientDtCommentStatus(i);
            try {
                commentStatusService.saveDtCommentStatus(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            commentStatusRepository.flush();
            data.add(obj);
        }
    }
    
}
