// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtCommunityRoleDataOnDemand;
import com.reltecsoft.lookon.domain.DtCommunityRoleIntegrationTest;
import com.reltecsoft.lookon.repository.CommunityRoleRepository;
import com.reltecsoft.lookon.service.CommunityRoleService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DtCommunityRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DtCommunityRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DtCommunityRoleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DtCommunityRoleIntegrationTest: @Transactional;
    
    @Autowired
    DtCommunityRoleDataOnDemand DtCommunityRoleIntegrationTest.dod;
    
    @Autowired
    CommunityRoleService DtCommunityRoleIntegrationTest.communityRoleService;
    
    @Autowired
    CommunityRoleRepository DtCommunityRoleIntegrationTest.communityRoleRepository;
    
    @Test
    public void DtCommunityRoleIntegrationTest.testCountAllDtCommunityRoles() {
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to initialize correctly", dod.getRandomDtCommunityRole());
        long count = communityRoleService.countAllDtCommunityRoles();
        Assert.assertTrue("Counter for 'DtCommunityRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DtCommunityRoleIntegrationTest.testFindDtCommunityRole() {
        DtCommunityRole obj = dod.getRandomDtCommunityRole();
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to provide an identifier", id);
        obj = communityRoleService.findDtCommunityRole(id);
        Assert.assertNotNull("Find method for 'DtCommunityRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DtCommunityRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DtCommunityRoleIntegrationTest.testFindAllDtCommunityRoles() {
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to initialize correctly", dod.getRandomDtCommunityRole());
        long count = communityRoleService.countAllDtCommunityRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'DtCommunityRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DtCommunityRole> result = communityRoleService.findAllDtCommunityRoles();
        Assert.assertNotNull("Find all method for 'DtCommunityRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DtCommunityRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DtCommunityRoleIntegrationTest.testFindDtCommunityRoleEntries() {
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to initialize correctly", dod.getRandomDtCommunityRole());
        long count = communityRoleService.countAllDtCommunityRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DtCommunityRole> result = communityRoleService.findDtCommunityRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DtCommunityRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DtCommunityRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DtCommunityRoleIntegrationTest.testSaveDtCommunityRole() {
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to initialize correctly", dod.getRandomDtCommunityRole());
        DtCommunityRole obj = dod.getNewTransientDtCommunityRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DtCommunityRole' identifier to be null", obj.getId());
        try {
            communityRoleService.saveDtCommunityRole(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        communityRoleRepository.flush();
        Assert.assertNotNull("Expected 'DtCommunityRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DtCommunityRoleIntegrationTest.testDeleteDtCommunityRole() {
        DtCommunityRole obj = dod.getRandomDtCommunityRole();
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtCommunityRole' failed to provide an identifier", id);
        obj = communityRoleService.findDtCommunityRole(id);
        communityRoleService.deleteDtCommunityRole(obj);
        communityRoleRepository.flush();
        Assert.assertNull("Failed to remove 'DtCommunityRole' with identifier '" + id + "'", communityRoleService.findDtCommunityRole(id));
    }
    
}
