// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtNotesRoleDataOnDemand;
import com.reltecsoft.lookon.domain.DtNotesRoleIntegrationTest;
import com.reltecsoft.lookon.repository.NotesRoleRepository;
import com.reltecsoft.lookon.service.NotesRoleService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DtNotesRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DtNotesRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DtNotesRoleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DtNotesRoleIntegrationTest: @Transactional;
    
    @Autowired
    DtNotesRoleDataOnDemand DtNotesRoleIntegrationTest.dod;
    
    @Autowired
    NotesRoleService DtNotesRoleIntegrationTest.notesRoleService;
    
    @Autowired
    NotesRoleRepository DtNotesRoleIntegrationTest.notesRoleRepository;
    
    @Test
    public void DtNotesRoleIntegrationTest.testCountAllDtNotesRoles() {
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to initialize correctly", dod.getRandomDtNotesRole());
        long count = notesRoleService.countAllDtNotesRoles();
        Assert.assertTrue("Counter for 'DtNotesRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DtNotesRoleIntegrationTest.testFindDtNotesRole() {
        DtNotesRole obj = dod.getRandomDtNotesRole();
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to provide an identifier", id);
        obj = notesRoleService.findDtNotesRole(id);
        Assert.assertNotNull("Find method for 'DtNotesRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DtNotesRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DtNotesRoleIntegrationTest.testFindAllDtNotesRoles() {
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to initialize correctly", dod.getRandomDtNotesRole());
        long count = notesRoleService.countAllDtNotesRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'DtNotesRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DtNotesRole> result = notesRoleService.findAllDtNotesRoles();
        Assert.assertNotNull("Find all method for 'DtNotesRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DtNotesRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DtNotesRoleIntegrationTest.testFindDtNotesRoleEntries() {
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to initialize correctly", dod.getRandomDtNotesRole());
        long count = notesRoleService.countAllDtNotesRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DtNotesRole> result = notesRoleService.findDtNotesRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DtNotesRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DtNotesRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DtNotesRoleIntegrationTest.testSaveDtNotesRole() {
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to initialize correctly", dod.getRandomDtNotesRole());
        DtNotesRole obj = dod.getNewTransientDtNotesRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DtNotesRole' identifier to be null", obj.getId());
        try {
            notesRoleService.saveDtNotesRole(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        notesRoleRepository.flush();
        Assert.assertNotNull("Expected 'DtNotesRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DtNotesRoleIntegrationTest.testDeleteDtNotesRole() {
        DtNotesRole obj = dod.getRandomDtNotesRole();
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtNotesRole' failed to provide an identifier", id);
        obj = notesRoleService.findDtNotesRole(id);
        notesRoleService.deleteDtNotesRole(obj);
        notesRoleRepository.flush();
        Assert.assertNull("Failed to remove 'DtNotesRole' with identifier '" + id + "'", notesRoleService.findDtNotesRole(id));
    }
    
}
