// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtPersonNetworkStatus;
import com.reltecsoft.lookon.domain.DtPersonNetworkStatusDataOnDemand;
import com.reltecsoft.lookon.repository.PersonNetworkStatusRepository;
import com.reltecsoft.lookon.service.PersonNetworkStatusService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DtPersonNetworkStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DtPersonNetworkStatusDataOnDemand: @Component;
    
    private Random DtPersonNetworkStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<DtPersonNetworkStatus> DtPersonNetworkStatusDataOnDemand.data;
    
    @Autowired
    PersonNetworkStatusService DtPersonNetworkStatusDataOnDemand.personNetworkStatusService;
    
    @Autowired
    PersonNetworkStatusRepository DtPersonNetworkStatusDataOnDemand.personNetworkStatusRepository;
    
    public DtPersonNetworkStatus DtPersonNetworkStatusDataOnDemand.getNewTransientDtPersonNetworkStatus(int index) {
        DtPersonNetworkStatus obj = new DtPersonNetworkStatus();
        setName(obj, index);
        return obj;
    }
    
    public void DtPersonNetworkStatusDataOnDemand.setName(DtPersonNetworkStatus obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public DtPersonNetworkStatus DtPersonNetworkStatusDataOnDemand.getSpecificDtPersonNetworkStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DtPersonNetworkStatus obj = data.get(index);
        Integer id = obj.getId();
        return personNetworkStatusService.findDtPersonNetworkStatus(id);
    }
    
    public DtPersonNetworkStatus DtPersonNetworkStatusDataOnDemand.getRandomDtPersonNetworkStatus() {
        init();
        DtPersonNetworkStatus obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return personNetworkStatusService.findDtPersonNetworkStatus(id);
    }
    
    public boolean DtPersonNetworkStatusDataOnDemand.modifyDtPersonNetworkStatus(DtPersonNetworkStatus obj) {
        return false;
    }
    
    public void DtPersonNetworkStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = personNetworkStatusService.findDtPersonNetworkStatusEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DtPersonNetworkStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DtPersonNetworkStatus>();
        for (int i = 0; i < 10; i++) {
            DtPersonNetworkStatus obj = getNewTransientDtPersonNetworkStatus(i);
            try {
                personNetworkStatusService.saveDtPersonNetworkStatus(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            personNetworkStatusRepository.flush();
            data.add(obj);
        }
    }
    
}
