// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtPersonNetworkStatusDataOnDemand;
import com.reltecsoft.lookon.domain.DtPersonNetworkStatusIntegrationTest;
import com.reltecsoft.lookon.repository.PersonNetworkStatusRepository;
import com.reltecsoft.lookon.service.PersonNetworkStatusService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DtPersonNetworkStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DtPersonNetworkStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DtPersonNetworkStatusIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DtPersonNetworkStatusIntegrationTest: @Transactional;
    
    @Autowired
    DtPersonNetworkStatusDataOnDemand DtPersonNetworkStatusIntegrationTest.dod;
    
    @Autowired
    PersonNetworkStatusService DtPersonNetworkStatusIntegrationTest.personNetworkStatusService;
    
    @Autowired
    PersonNetworkStatusRepository DtPersonNetworkStatusIntegrationTest.personNetworkStatusRepository;
    
    @Test
    public void DtPersonNetworkStatusIntegrationTest.testCountAllDtPersonNetworkStatuses() {
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to initialize correctly", dod.getRandomDtPersonNetworkStatus());
        long count = personNetworkStatusService.countAllDtPersonNetworkStatuses();
        Assert.assertTrue("Counter for 'DtPersonNetworkStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DtPersonNetworkStatusIntegrationTest.testFindDtPersonNetworkStatus() {
        DtPersonNetworkStatus obj = dod.getRandomDtPersonNetworkStatus();
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to provide an identifier", id);
        obj = personNetworkStatusService.findDtPersonNetworkStatus(id);
        Assert.assertNotNull("Find method for 'DtPersonNetworkStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DtPersonNetworkStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DtPersonNetworkStatusIntegrationTest.testFindAllDtPersonNetworkStatuses() {
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to initialize correctly", dod.getRandomDtPersonNetworkStatus());
        long count = personNetworkStatusService.countAllDtPersonNetworkStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'DtPersonNetworkStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DtPersonNetworkStatus> result = personNetworkStatusService.findAllDtPersonNetworkStatuses();
        Assert.assertNotNull("Find all method for 'DtPersonNetworkStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DtPersonNetworkStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DtPersonNetworkStatusIntegrationTest.testFindDtPersonNetworkStatusEntries() {
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to initialize correctly", dod.getRandomDtPersonNetworkStatus());
        long count = personNetworkStatusService.countAllDtPersonNetworkStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DtPersonNetworkStatus> result = personNetworkStatusService.findDtPersonNetworkStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DtPersonNetworkStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DtPersonNetworkStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DtPersonNetworkStatusIntegrationTest.testSaveDtPersonNetworkStatus() {
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to initialize correctly", dod.getRandomDtPersonNetworkStatus());
        DtPersonNetworkStatus obj = dod.getNewTransientDtPersonNetworkStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DtPersonNetworkStatus' identifier to be null", obj.getId());
        try {
            personNetworkStatusService.saveDtPersonNetworkStatus(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        personNetworkStatusRepository.flush();
        Assert.assertNotNull("Expected 'DtPersonNetworkStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DtPersonNetworkStatusIntegrationTest.testDeleteDtPersonNetworkStatus() {
        DtPersonNetworkStatus obj = dod.getRandomDtPersonNetworkStatus();
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtPersonNetworkStatus' failed to provide an identifier", id);
        obj = personNetworkStatusService.findDtPersonNetworkStatus(id);
        personNetworkStatusService.deleteDtPersonNetworkStatus(obj);
        personNetworkStatusRepository.flush();
        Assert.assertNull("Failed to remove 'DtPersonNetworkStatus' with identifier '" + id + "'", personNetworkStatusService.findDtPersonNetworkStatus(id));
    }
    
}
