// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtWorkStatusDataOnDemand;
import com.reltecsoft.lookon.domain.DtWorkStatusIntegrationTest;
import com.reltecsoft.lookon.repository.WorkStatusRepository;
import com.reltecsoft.lookon.service.WorkStatusService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DtWorkStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DtWorkStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DtWorkStatusIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DtWorkStatusIntegrationTest: @Transactional;
    
    @Autowired
    DtWorkStatusDataOnDemand DtWorkStatusIntegrationTest.dod;
    
    @Autowired
    WorkStatusService DtWorkStatusIntegrationTest.workStatusService;
    
    @Autowired
    WorkStatusRepository DtWorkStatusIntegrationTest.workStatusRepository;
    
    @Test
    public void DtWorkStatusIntegrationTest.testCountAllDtWorkStatuses() {
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to initialize correctly", dod.getRandomDtWorkStatus());
        long count = workStatusService.countAllDtWorkStatuses();
        Assert.assertTrue("Counter for 'DtWorkStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DtWorkStatusIntegrationTest.testFindDtWorkStatus() {
        DtWorkStatus obj = dod.getRandomDtWorkStatus();
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to provide an identifier", id);
        obj = workStatusService.findDtWorkStatus(id);
        Assert.assertNotNull("Find method for 'DtWorkStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DtWorkStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DtWorkStatusIntegrationTest.testFindAllDtWorkStatuses() {
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to initialize correctly", dod.getRandomDtWorkStatus());
        long count = workStatusService.countAllDtWorkStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'DtWorkStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DtWorkStatus> result = workStatusService.findAllDtWorkStatuses();
        Assert.assertNotNull("Find all method for 'DtWorkStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DtWorkStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DtWorkStatusIntegrationTest.testFindDtWorkStatusEntries() {
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to initialize correctly", dod.getRandomDtWorkStatus());
        long count = workStatusService.countAllDtWorkStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DtWorkStatus> result = workStatusService.findDtWorkStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DtWorkStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DtWorkStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DtWorkStatusIntegrationTest.testSaveDtWorkStatus() {
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to initialize correctly", dod.getRandomDtWorkStatus());
        DtWorkStatus obj = dod.getNewTransientDtWorkStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DtWorkStatus' identifier to be null", obj.getId());
        try {
            workStatusService.saveDtWorkStatus(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        workStatusRepository.flush();
        Assert.assertNotNull("Expected 'DtWorkStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DtWorkStatusIntegrationTest.testDeleteDtWorkStatus() {
        DtWorkStatus obj = dod.getRandomDtWorkStatus();
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DtWorkStatus' failed to provide an identifier", id);
        obj = workStatusService.findDtWorkStatus(id);
        workStatusService.deleteDtWorkStatus(obj);
        workStatusRepository.flush();
        Assert.assertNull("Failed to remove 'DtWorkStatus' with identifier '" + id + "'", workStatusService.findDtWorkStatus(id));
    }
    
}
