// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.Chat;
import com.reltecsoft.lookon.domain.ChatDataOnDemand;
import com.reltecsoft.lookon.domain.MediaDataOnDemand;
import com.reltecsoft.lookon.domain.Message;
import com.reltecsoft.lookon.domain.MessageDataOnDemand;
import com.reltecsoft.lookon.domain.Person;
import com.reltecsoft.lookon.domain.PersonDataOnDemand;
import com.reltecsoft.lookon.repository.MessageRepository;
import com.reltecsoft.lookon.service.MessageService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MessageDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MessageDataOnDemand: @Component;
    
    private Random MessageDataOnDemand.rnd = new SecureRandom();
    
    private List<Message> MessageDataOnDemand.data;
    
    @Autowired
    ChatDataOnDemand MessageDataOnDemand.chatDataOnDemand;
    
    @Autowired
    MediaDataOnDemand MessageDataOnDemand.mediaDataOnDemand;
    
    @Autowired
    PersonDataOnDemand MessageDataOnDemand.personDataOnDemand;
    
    @Autowired
    MessageService MessageDataOnDemand.messageService;
    
    @Autowired
    MessageRepository MessageDataOnDemand.messageRepository;
    
    public Message MessageDataOnDemand.getNewTransientMessage(int index) {
        Message obj = new Message();
        setChat(obj, index);
        setMessageText(obj, index);
        setMessageTime(obj, index);
        setPerson(obj, index);
        return obj;
    }
    
    public void MessageDataOnDemand.setChat(Message obj, int index) {
        Chat chat = chatDataOnDemand.getRandomChat();
        obj.setChat(chat);
    }
    
    public void MessageDataOnDemand.setMessageText(Message obj, int index) {
        String messageText = "messageText_" + index;
        if (messageText.length() > 2048) {
            messageText = messageText.substring(0, 2048);
        }
        obj.setMessageText(messageText);
    }
    
    public void MessageDataOnDemand.setMessageTime(Message obj, int index) {
        Date messageTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setMessageTime(messageTime);
    }
    
    public void MessageDataOnDemand.setPerson(Message obj, int index) {
        Person person = personDataOnDemand.getRandomPerson();
        obj.setPerson(person);
    }
    
    public Message MessageDataOnDemand.getSpecificMessage(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Message obj = data.get(index);
        Long id = obj.getId();
        return messageService.findMessage(id);
    }
    
    public Message MessageDataOnDemand.getRandomMessage() {
        init();
        Message obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return messageService.findMessage(id);
    }
    
    public boolean MessageDataOnDemand.modifyMessage(Message obj) {
        return false;
    }
    
    public void MessageDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = messageService.findMessageEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Message' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Message>();
        for (int i = 0; i < 10; i++) {
            Message obj = getNewTransientMessage(i);
            try {
                messageService.saveMessage(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            messageRepository.flush();
            data.add(obj);
        }
    }
    
}
