// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.NotesDataOnDemand;
import com.reltecsoft.lookon.domain.NotesIntegrationTest;
import com.reltecsoft.lookon.repository.NotesRepository;
import com.reltecsoft.lookon.service.NotesService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NotesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NotesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NotesIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NotesIntegrationTest: @Transactional;
    
    @Autowired
    NotesDataOnDemand NotesIntegrationTest.dod;
    
    @Autowired
    NotesService NotesIntegrationTest.notesService;
    
    @Autowired
    NotesRepository NotesIntegrationTest.notesRepository;
    
    @Test
    public void NotesIntegrationTest.testCountAllNoteses() {
        Assert.assertNotNull("Data on demand for 'Notes' failed to initialize correctly", dod.getRandomNotes());
        long count = notesService.countAllNoteses();
        Assert.assertTrue("Counter for 'Notes' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NotesIntegrationTest.testFindNotes() {
        Notes obj = dod.getRandomNotes();
        Assert.assertNotNull("Data on demand for 'Notes' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notes' failed to provide an identifier", id);
        obj = notesService.findNotes(id);
        Assert.assertNotNull("Find method for 'Notes' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Notes' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NotesIntegrationTest.testFindAllNoteses() {
        Assert.assertNotNull("Data on demand for 'Notes' failed to initialize correctly", dod.getRandomNotes());
        long count = notesService.countAllNoteses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Notes', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Notes> result = notesService.findAllNoteses();
        Assert.assertNotNull("Find all method for 'Notes' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Notes' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NotesIntegrationTest.testFindNotesEntries() {
        Assert.assertNotNull("Data on demand for 'Notes' failed to initialize correctly", dod.getRandomNotes());
        long count = notesService.countAllNoteses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Notes> result = notesService.findNotesEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Notes' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Notes' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NotesIntegrationTest.testSaveNotes() {
        Assert.assertNotNull("Data on demand for 'Notes' failed to initialize correctly", dod.getRandomNotes());
        Notes obj = dod.getNewTransientNotes(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Notes' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Notes' identifier to be null", obj.getId());
        try {
            notesService.saveNotes(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        notesRepository.flush();
        Assert.assertNotNull("Expected 'Notes' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NotesIntegrationTest.testDeleteNotes() {
        Notes obj = dod.getRandomNotes();
        Assert.assertNotNull("Data on demand for 'Notes' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Notes' failed to provide an identifier", id);
        obj = notesService.findNotes(id);
        notesService.deleteNotes(obj);
        notesRepository.flush();
        Assert.assertNull("Failed to remove 'Notes' with identifier '" + id + "'", notesService.findNotes(id));
    }
    
}
