// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.NotesTypeDataOnDemand;
import com.reltecsoft.lookon.domain.NotesTypeIntegrationTest;
import com.reltecsoft.lookon.repository.NotesTypeRepository;
import com.reltecsoft.lookon.service.NotesTypeService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NotesTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NotesTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NotesTypeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NotesTypeIntegrationTest: @Transactional;
    
    @Autowired
    NotesTypeDataOnDemand NotesTypeIntegrationTest.dod;
    
    @Autowired
    NotesTypeService NotesTypeIntegrationTest.notesTypeService;
    
    @Autowired
    NotesTypeRepository NotesTypeIntegrationTest.notesTypeRepository;
    
    @Test
    public void NotesTypeIntegrationTest.testCountAllNotesTypes() {
        Assert.assertNotNull("Data on demand for 'NotesType' failed to initialize correctly", dod.getRandomNotesType());
        long count = notesTypeService.countAllNotesTypes();
        Assert.assertTrue("Counter for 'NotesType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NotesTypeIntegrationTest.testFindNotesType() {
        NotesType obj = dod.getRandomNotesType();
        Assert.assertNotNull("Data on demand for 'NotesType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NotesType' failed to provide an identifier", id);
        obj = notesTypeService.findNotesType(id);
        Assert.assertNotNull("Find method for 'NotesType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'NotesType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NotesTypeIntegrationTest.testFindAllNotesTypes() {
        Assert.assertNotNull("Data on demand for 'NotesType' failed to initialize correctly", dod.getRandomNotesType());
        long count = notesTypeService.countAllNotesTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'NotesType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<NotesType> result = notesTypeService.findAllNotesTypes();
        Assert.assertNotNull("Find all method for 'NotesType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'NotesType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NotesTypeIntegrationTest.testFindNotesTypeEntries() {
        Assert.assertNotNull("Data on demand for 'NotesType' failed to initialize correctly", dod.getRandomNotesType());
        long count = notesTypeService.countAllNotesTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<NotesType> result = notesTypeService.findNotesTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'NotesType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'NotesType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NotesTypeIntegrationTest.testFlush() {
        NotesType obj = dod.getRandomNotesType();
        Assert.assertNotNull("Data on demand for 'NotesType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NotesType' failed to provide an identifier", id);
        obj = notesTypeService.findNotesType(id);
        Assert.assertNotNull("Find method for 'NotesType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNotesType(obj);
        Integer currentVersion = obj.getVersion();
        notesTypeRepository.flush();
        Assert.assertTrue("Version for 'NotesType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NotesTypeIntegrationTest.testUpdateNotesTypeUpdate() {
        NotesType obj = dod.getRandomNotesType();
        Assert.assertNotNull("Data on demand for 'NotesType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NotesType' failed to provide an identifier", id);
        obj = notesTypeService.findNotesType(id);
        boolean modified =  dod.modifyNotesType(obj);
        Integer currentVersion = obj.getVersion();
        NotesType merged = notesTypeService.updateNotesType(obj);
        notesTypeRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'NotesType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NotesTypeIntegrationTest.testSaveNotesType() {
        Assert.assertNotNull("Data on demand for 'NotesType' failed to initialize correctly", dod.getRandomNotesType());
        NotesType obj = dod.getNewTransientNotesType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'NotesType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'NotesType' identifier to be null", obj.getId());
        try {
            notesTypeService.saveNotesType(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        notesTypeRepository.flush();
        Assert.assertNotNull("Expected 'NotesType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NotesTypeIntegrationTest.testDeleteNotesType() {
        NotesType obj = dod.getRandomNotesType();
        Assert.assertNotNull("Data on demand for 'NotesType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NotesType' failed to provide an identifier", id);
        obj = notesTypeService.findNotesType(id);
        notesTypeService.deleteNotesType(obj);
        notesTypeRepository.flush();
        Assert.assertNull("Failed to remove 'NotesType' with identifier '" + id + "'", notesTypeService.findNotesType(id));
    }
    
}
