// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtNotesType;
import com.reltecsoft.lookon.domain.DtNotesTypeDataOnDemand;
import com.reltecsoft.lookon.domain.MediaDataOnDemand;
import com.reltecsoft.lookon.domain.Notes;
import com.reltecsoft.lookon.domain.NotesDataOnDemand;
import com.reltecsoft.lookon.domain.Person;
import com.reltecsoft.lookon.domain.PersonDataOnDemand;
import com.reltecsoft.lookon.repository.NotesRepository;
import com.reltecsoft.lookon.service.NotesService;
import java.security.SecureRandom;
import java.sql.Clob;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NotesDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NotesDataOnDemand: @Component;
    
    private Random NotesDataOnDemand.rnd = new SecureRandom();
    
    private List<Notes> NotesDataOnDemand.data;
    
    @Autowired
    MediaDataOnDemand NotesDataOnDemand.mediaDataOnDemand;
    
    @Autowired
    PersonDataOnDemand NotesDataOnDemand.personDataOnDemand;
    
    @Autowired
    DtNotesTypeDataOnDemand NotesDataOnDemand.dtNotesTypeDataOnDemand;
    
    @Autowired
    NotesService NotesDataOnDemand.notesService;
    
    @Autowired
    NotesRepository NotesDataOnDemand.notesRepository;
    
    public Notes NotesDataOnDemand.getNewTransientNotes(int index) {
        Notes obj = new Notes();
        setNote(obj, index);
        setPersonId(obj, index);
        setTypeId(obj, index);
        return obj;
    }
    
    public void NotesDataOnDemand.setNote(Notes obj, int index) {
        Clob note = null;
        obj.setNote(note);
    }
    
    public void NotesDataOnDemand.setPersonId(Notes obj, int index) {
        Person personId = personDataOnDemand.getRandomPerson();
        obj.setPersonId(personId);
    }
    
    public void NotesDataOnDemand.setTypeId(Notes obj, int index) {
        DtNotesType typeId = dtNotesTypeDataOnDemand.getRandomDtNotesType();
        obj.setTypeId(typeId);
    }
    
    public Notes NotesDataOnDemand.getSpecificNotes(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Notes obj = data.get(index);
        Long id = obj.getId();
        return notesService.findNotes(id);
    }
    
    public Notes NotesDataOnDemand.getRandomNotes() {
        init();
        Notes obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return notesService.findNotes(id);
    }
    
    public boolean NotesDataOnDemand.modifyNotes(Notes obj) {
        return false;
    }
    
    public void NotesDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = notesService.findNotesEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Notes' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Notes>();
        for (int i = 0; i < 10; i++) {
            Notes obj = getNewTransientNotes(i);
            try {
                notesService.saveNotes(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            notesRepository.flush();
            data.add(obj);
        }
    }
    
}
