// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.PrivateMessageDataOnDemand;
import com.reltecsoft.lookon.domain.PrivateMessageIntegrationTest;
import com.reltecsoft.lookon.repository.PrivateMessageRepository;
import com.reltecsoft.lookon.service.PrivateMessageService;
import java.math.BigDecimal;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PrivateMessageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PrivateMessageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PrivateMessageIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PrivateMessageIntegrationTest: @Transactional;
    
    @Autowired
    PrivateMessageDataOnDemand PrivateMessageIntegrationTest.dod;
    
    @Autowired
    PrivateMessageService PrivateMessageIntegrationTest.privateMessageService;
    
    @Autowired
    PrivateMessageRepository PrivateMessageIntegrationTest.privateMessageRepository;
    
    @Test
    public void PrivateMessageIntegrationTest.testCountAllPrivateMessages() {
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to initialize correctly", dod.getRandomPrivateMessage());
        long count = privateMessageService.countAllPrivateMessages();
        Assert.assertTrue("Counter for 'PrivateMessage' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PrivateMessageIntegrationTest.testFindPrivateMessage() {
        PrivateMessage obj = dod.getRandomPrivateMessage();
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to initialize correctly", obj);
        BigDecimal id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to provide an identifier", id);
        obj = privateMessageService.findPrivateMessage(id);
        Assert.assertNotNull("Find method for 'PrivateMessage' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PrivateMessage' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PrivateMessageIntegrationTest.testFindAllPrivateMessages() {
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to initialize correctly", dod.getRandomPrivateMessage());
        long count = privateMessageService.countAllPrivateMessages();
        Assert.assertTrue("Too expensive to perform a find all test for 'PrivateMessage', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PrivateMessage> result = privateMessageService.findAllPrivateMessages();
        Assert.assertNotNull("Find all method for 'PrivateMessage' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PrivateMessage' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PrivateMessageIntegrationTest.testFindPrivateMessageEntries() {
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to initialize correctly", dod.getRandomPrivateMessage());
        long count = privateMessageService.countAllPrivateMessages();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PrivateMessage> result = privateMessageService.findPrivateMessageEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PrivateMessage' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PrivateMessage' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PrivateMessageIntegrationTest.testSavePrivateMessage() {
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to initialize correctly", dod.getRandomPrivateMessage());
        PrivateMessage obj = dod.getNewTransientPrivateMessage(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PrivateMessage' identifier to be null", obj.getId());
        try {
            privateMessageService.savePrivateMessage(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        privateMessageRepository.flush();
        Assert.assertNotNull("Expected 'PrivateMessage' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PrivateMessageIntegrationTest.testDeletePrivateMessage() {
        PrivateMessage obj = dod.getRandomPrivateMessage();
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to initialize correctly", obj);
        BigDecimal id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PrivateMessage' failed to provide an identifier", id);
        obj = privateMessageService.findPrivateMessage(id);
        privateMessageService.deletePrivateMessage(obj);
        privateMessageRepository.flush();
        Assert.assertNull("Failed to remove 'PrivateMessage' with identifier '" + id + "'", privateMessageService.findPrivateMessage(id));
    }
    
}
