// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.DtVacancyStatus;
import com.reltecsoft.lookon.domain.DtVacancyStatusDataOnDemand;
import com.reltecsoft.lookon.domain.RealCompany;
import com.reltecsoft.lookon.domain.RealCompanyDataOnDemand;
import com.reltecsoft.lookon.domain.Vacancy;
import com.reltecsoft.lookon.domain.VacancyDataOnDemand;
import com.reltecsoft.lookon.repository.VacancyRepository;
import com.reltecsoft.lookon.service.VacancyService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect VacancyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VacancyDataOnDemand: @Component;
    
    private Random VacancyDataOnDemand.rnd = new SecureRandom();
    
    private List<Vacancy> VacancyDataOnDemand.data;
    
    @Autowired
    RealCompanyDataOnDemand VacancyDataOnDemand.realCompanyDataOnDemand;
    
    @Autowired
    DtVacancyStatusDataOnDemand VacancyDataOnDemand.dtVacancyStatusDataOnDemand;
    
    @Autowired
    VacancyService VacancyDataOnDemand.vacancyService;
    
    @Autowired
    VacancyRepository VacancyDataOnDemand.vacancyRepository;
    
    public Vacancy VacancyDataOnDemand.getNewTransientVacancy(int index) {
        Vacancy obj = new Vacancy();
        setCompanyId(obj, index);
        setName(obj, index);
        setStatusId(obj, index);
        return obj;
    }
    
    public void VacancyDataOnDemand.setCompanyId(Vacancy obj, int index) {
        RealCompany companyId = realCompanyDataOnDemand.getRandomRealCompany();
        obj.setCompanyId(companyId);
    }
    
    public void VacancyDataOnDemand.setName(Vacancy obj, int index) {
        String name = "name_" + index;
        if (name.length() > 255) {
            name = name.substring(0, 255);
        }
        obj.setName(name);
    }
    
    public void VacancyDataOnDemand.setStatusId(Vacancy obj, int index) {
        DtVacancyStatus statusId = dtVacancyStatusDataOnDemand.getRandomDtVacancyStatus();
        obj.setStatusId(statusId);
    }
    
    public Vacancy VacancyDataOnDemand.getSpecificVacancy(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Vacancy obj = data.get(index);
        Long id = obj.getId();
        return vacancyService.findVacancy(id);
    }
    
    public Vacancy VacancyDataOnDemand.getRandomVacancy() {
        init();
        Vacancy obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return vacancyService.findVacancy(id);
    }
    
    public boolean VacancyDataOnDemand.modifyVacancy(Vacancy obj) {
        return false;
    }
    
    public void VacancyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = vacancyService.findVacancyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Vacancy' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Vacancy>();
        for (int i = 0; i < 10; i++) {
            Vacancy obj = getNewTransientVacancy(i);
            try {
                vacancyService.saveVacancy(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            vacancyRepository.flush();
            data.add(obj);
        }
    }
    
}
