// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.WorkspaceDataOnDemand;
import com.reltecsoft.lookon.domain.WorkspaceIntegrationTest;
import com.reltecsoft.lookon.repository.WorkspaceRepository;
import com.reltecsoft.lookon.service.WorkspaceService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkspaceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkspaceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkspaceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WorkspaceIntegrationTest: @Transactional;
    
    @Autowired
    WorkspaceDataOnDemand WorkspaceIntegrationTest.dod;
    
    @Autowired
    WorkspaceService WorkspaceIntegrationTest.workspaceService;
    
    @Autowired
    WorkspaceRepository WorkspaceIntegrationTest.workspaceRepository;
    
    @Test
    public void WorkspaceIntegrationTest.testCountAllWorkspaces() {
        Assert.assertNotNull("Data on demand for 'Workspace' failed to initialize correctly", dod.getRandomWorkspace());
        long count = workspaceService.countAllWorkspaces();
        Assert.assertTrue("Counter for 'Workspace' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkspaceIntegrationTest.testFindWorkspace() {
        Workspace obj = dod.getRandomWorkspace();
        Assert.assertNotNull("Data on demand for 'Workspace' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Workspace' failed to provide an identifier", id);
        obj = workspaceService.findWorkspace(id);
        Assert.assertNotNull("Find method for 'Workspace' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Workspace' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkspaceIntegrationTest.testFindAllWorkspaces() {
        Assert.assertNotNull("Data on demand for 'Workspace' failed to initialize correctly", dod.getRandomWorkspace());
        long count = workspaceService.countAllWorkspaces();
        Assert.assertTrue("Too expensive to perform a find all test for 'Workspace', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Workspace> result = workspaceService.findAllWorkspaces();
        Assert.assertNotNull("Find all method for 'Workspace' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Workspace' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkspaceIntegrationTest.testFindWorkspaceEntries() {
        Assert.assertNotNull("Data on demand for 'Workspace' failed to initialize correctly", dod.getRandomWorkspace());
        long count = workspaceService.countAllWorkspaces();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Workspace> result = workspaceService.findWorkspaceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Workspace' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Workspace' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkspaceIntegrationTest.testSaveWorkspace() {
        Assert.assertNotNull("Data on demand for 'Workspace' failed to initialize correctly", dod.getRandomWorkspace());
        Workspace obj = dod.getNewTransientWorkspace(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Workspace' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Workspace' identifier to be null", obj.getId());
        try {
            workspaceService.saveWorkspace(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        workspaceRepository.flush();
        Assert.assertNotNull("Expected 'Workspace' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WorkspaceIntegrationTest.testDeleteWorkspace() {
        Workspace obj = dod.getRandomWorkspace();
        Assert.assertNotNull("Data on demand for 'Workspace' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Workspace' failed to provide an identifier", id);
        obj = workspaceService.findWorkspace(id);
        workspaceService.deleteWorkspace(obj);
        workspaceRepository.flush();
        Assert.assertNull("Failed to remove 'Workspace' with identifier '" + id + "'", workspaceService.findWorkspace(id));
    }
    
}
