// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.WorkStatusDataOnDemand;
import com.reltecsoft.lookon.domain.WorkStatusIntegrationTest;
import com.reltecsoft.lookon.repository.WorkStatusRepository;
import com.reltecsoft.lookon.service.WorkStatusService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkStatusIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkStatusIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkStatusIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WorkStatusIntegrationTest: @Transactional;
    
    @Autowired
    WorkStatusDataOnDemand WorkStatusIntegrationTest.dod;
    
    @Autowired
    WorkStatusService WorkStatusIntegrationTest.workStatusService;
    
    @Autowired
    WorkStatusRepository WorkStatusIntegrationTest.workStatusRepository;
    
    @Test
    public void WorkStatusIntegrationTest.testCountAllWorkStatuses() {
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to initialize correctly", dod.getRandomWorkStatus());
        long count = workStatusService.countAllWorkStatuses();
        Assert.assertTrue("Counter for 'WorkStatus' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkStatusIntegrationTest.testFindWorkStatus() {
        WorkStatus obj = dod.getRandomWorkStatus();
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to provide an identifier", id);
        obj = workStatusService.findWorkStatus(id);
        Assert.assertNotNull("Find method for 'WorkStatus' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WorkStatus' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkStatusIntegrationTest.testFindAllWorkStatuses() {
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to initialize correctly", dod.getRandomWorkStatus());
        long count = workStatusService.countAllWorkStatuses();
        Assert.assertTrue("Too expensive to perform a find all test for 'WorkStatus', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WorkStatus> result = workStatusService.findAllWorkStatuses();
        Assert.assertNotNull("Find all method for 'WorkStatus' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WorkStatus' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkStatusIntegrationTest.testFindWorkStatusEntries() {
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to initialize correctly", dod.getRandomWorkStatus());
        long count = workStatusService.countAllWorkStatuses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WorkStatus> result = workStatusService.findWorkStatusEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WorkStatus' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WorkStatus' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkStatusIntegrationTest.testFlush() {
        WorkStatus obj = dod.getRandomWorkStatus();
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to provide an identifier", id);
        obj = workStatusService.findWorkStatus(id);
        Assert.assertNotNull("Find method for 'WorkStatus' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWorkStatus(obj);
        Integer currentVersion = obj.getVersion();
        workStatusRepository.flush();
        Assert.assertTrue("Version for 'WorkStatus' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkStatusIntegrationTest.testUpdateWorkStatusUpdate() {
        WorkStatus obj = dod.getRandomWorkStatus();
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to provide an identifier", id);
        obj = workStatusService.findWorkStatus(id);
        boolean modified =  dod.modifyWorkStatus(obj);
        Integer currentVersion = obj.getVersion();
        WorkStatus merged = workStatusService.updateWorkStatus(obj);
        workStatusRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WorkStatus' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkStatusIntegrationTest.testSaveWorkStatus() {
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to initialize correctly", dod.getRandomWorkStatus());
        WorkStatus obj = dod.getNewTransientWorkStatus(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WorkStatus' identifier to be null", obj.getId());
        try {
            workStatusService.saveWorkStatus(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        workStatusRepository.flush();
        Assert.assertNotNull("Expected 'WorkStatus' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WorkStatusIntegrationTest.testDeleteWorkStatus() {
        WorkStatus obj = dod.getRandomWorkStatus();
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkStatus' failed to provide an identifier", id);
        obj = workStatusService.findWorkStatus(id);
        workStatusService.deleteWorkStatus(obj);
        workStatusRepository.flush();
        Assert.assertNull("Failed to remove 'WorkStatus' with identifier '" + id + "'", workStatusService.findWorkStatus(id));
    }
    
}
