// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.WorkplaceDataOnDemand;
import com.reltecsoft.lookon.domain.WorkplaceIntegrationTest;
import com.reltecsoft.lookon.repository.WorkplaceRepository;
import com.reltecsoft.lookon.service.WorkplaceService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkplaceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkplaceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkplaceIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WorkplaceIntegrationTest: @Transactional;
    
    @Autowired
    WorkplaceDataOnDemand WorkplaceIntegrationTest.dod;
    
    @Autowired
    WorkplaceService WorkplaceIntegrationTest.workplaceService;
    
    @Autowired
    WorkplaceRepository WorkplaceIntegrationTest.workplaceRepository;
    
    @Test
    public void WorkplaceIntegrationTest.testCountAllWorkplaces() {
        Assert.assertNotNull("Data on demand for 'Workplace' failed to initialize correctly", dod.getRandomWorkplace());
        long count = workplaceService.countAllWorkplaces();
        Assert.assertTrue("Counter for 'Workplace' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkplaceIntegrationTest.testFindWorkplace() {
        Workplace obj = dod.getRandomWorkplace();
        Assert.assertNotNull("Data on demand for 'Workplace' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Workplace' failed to provide an identifier", id);
        obj = workplaceService.findWorkplace(id);
        Assert.assertNotNull("Find method for 'Workplace' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Workplace' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkplaceIntegrationTest.testFindAllWorkplaces() {
        Assert.assertNotNull("Data on demand for 'Workplace' failed to initialize correctly", dod.getRandomWorkplace());
        long count = workplaceService.countAllWorkplaces();
        Assert.assertTrue("Too expensive to perform a find all test for 'Workplace', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Workplace> result = workplaceService.findAllWorkplaces();
        Assert.assertNotNull("Find all method for 'Workplace' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Workplace' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkplaceIntegrationTest.testFindWorkplaceEntries() {
        Assert.assertNotNull("Data on demand for 'Workplace' failed to initialize correctly", dod.getRandomWorkplace());
        long count = workplaceService.countAllWorkplaces();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Workplace> result = workplaceService.findWorkplaceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Workplace' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Workplace' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkplaceIntegrationTest.testSaveWorkplace() {
        Assert.assertNotNull("Data on demand for 'Workplace' failed to initialize correctly", dod.getRandomWorkplace());
        Workplace obj = dod.getNewTransientWorkplace(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Workplace' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Workplace' identifier to be null", obj.getId());
        try {
            workplaceService.saveWorkplace(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        workplaceRepository.flush();
        Assert.assertNotNull("Expected 'Workplace' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WorkplaceIntegrationTest.testDeleteWorkplace() {
        Workplace obj = dod.getRandomWorkplace();
        Assert.assertNotNull("Data on demand for 'Workplace' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Workplace' failed to provide an identifier", id);
        obj = workplaceService.findWorkplace(id);
        workplaceService.deleteWorkplace(obj);
        workplaceRepository.flush();
        Assert.assertNull("Failed to remove 'Workplace' with identifier '" + id + "'", workplaceService.findWorkplace(id));
    }
    
}
