// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.CompanyDataOnDemand;
import com.reltecsoft.lookon.domain.UserWorkDataOnDemand;
import com.reltecsoft.lookon.domain.WorkHistory;
import com.reltecsoft.lookon.domain.WorkHistoryDataOnDemand;
import com.reltecsoft.lookon.domain.WorkStatusDataOnDemand;
import com.reltecsoft.lookon.repository.WorkHistoryRepository;
import com.reltecsoft.lookon.service.WorkHistoryService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect WorkHistoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WorkHistoryDataOnDemand: @Component;
    
    private Random WorkHistoryDataOnDemand.rnd = new SecureRandom();
    
    private List<WorkHistory> WorkHistoryDataOnDemand.data;
    
    @Autowired
    CompanyDataOnDemand WorkHistoryDataOnDemand.companyDataOnDemand;
    
    @Autowired
    WorkStatusDataOnDemand WorkHistoryDataOnDemand.workStatusDataOnDemand;
    
    @Autowired
    UserWorkDataOnDemand WorkHistoryDataOnDemand.userWorkDataOnDemand;
    
    @Autowired
    WorkHistoryService WorkHistoryDataOnDemand.workHistoryService;
    
    @Autowired
    WorkHistoryRepository WorkHistoryDataOnDemand.workHistoryRepository;
    
    public WorkHistory WorkHistoryDataOnDemand.getNewTransientWorkHistory(int index) {
        WorkHistory obj = new WorkHistory();
        return obj;
    }
    
    public WorkHistory WorkHistoryDataOnDemand.getSpecificWorkHistory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WorkHistory obj = data.get(index);
        Long id = obj.getId();
        return workHistoryService.findWorkHistory(id);
    }
    
    public WorkHistory WorkHistoryDataOnDemand.getRandomWorkHistory() {
        init();
        WorkHistory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return workHistoryService.findWorkHistory(id);
    }
    
    public boolean WorkHistoryDataOnDemand.modifyWorkHistory(WorkHistory obj) {
        return false;
    }
    
    public void WorkHistoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = workHistoryService.findWorkHistoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WorkHistory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WorkHistory>();
        for (int i = 0; i < 10; i++) {
            WorkHistory obj = getNewTransientWorkHistory(i);
            try {
                workHistoryService.saveWorkHistory(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            workHistoryRepository.flush();
            data.add(obj);
        }
    }
    
}
