// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.CommunityAlbumPK;
import java.io.Serializable;

privileged aspect CommunityAlbumPK_Roo_Serializable {
    
    declare parents: CommunityAlbumPK implements Serializable;
    
    private static final long CommunityAlbumPK.serialVersionUID = 1L;
    
}
