// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.CompanyStatus;

privileged aspect CompanyStatus_Roo_JavaBean {
    
    public String CompanyStatus.getName() {
        return this.name;
    }
    
    public void CompanyStatus.setName(String name) {
        this.name = name;
    }
    
}
