// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.MediaType;

privileged aspect MediaType_Roo_JavaBean {
    
    public String MediaType.getTypeName() {
        return this.typeName;
    }
    
    public void MediaType.setTypeName(String typeName) {
        this.typeName = typeName;
    }
    
}
