// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.PersonBlacklistPK;
import java.io.Serializable;

privileged aspect PersonBlacklistPK_Roo_Serializable {
    
    declare parents: PersonBlacklistPK implements Serializable;
    
    private static final long PersonBlacklistPK.serialVersionUID = 1L;
    
}
