// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.PersonFriendPK;
import java.io.Serializable;

privileged aspect PersonFriendPK_Roo_Serializable {
    
    declare parents: PersonFriendPK implements Serializable;
    
    private static final long PersonFriendPK.serialVersionUID = 1L;
    
}
