// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.PersonChatPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PersonChatPK_Roo_Configurable {
    
    declare @type: PersonChatPK: @Configurable;
    
}
