// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.PersonStatus;

privileged aspect PersonStatus_Roo_JavaBean {
    
    public String PersonStatus.getName() {
        return this.name;
    }
    
    public void PersonStatus.setName(String name) {
        this.name = name;
    }
    
}
