// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.PersonRatingPK;
import java.io.Serializable;

privileged aspect PersonRatingPK_Roo_Serializable {
    
    declare parents: PersonRatingPK implements Serializable;
    
    private static final long PersonRatingPK.serialVersionUID = 1L;
    
}
