// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.Phone;

privileged aspect Phone_Roo_JavaBean {
    
    public String Phone.getPhone() {
        return this.phone;
    }
    
    public void Phone.setPhone(String phone) {
        this.phone = phone;
    }
    
}
