// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.ResumeRatingPK;
import java.io.Serializable;

privileged aspect ResumeRatingPK_Roo_Serializable {
    
    declare parents: ResumeRatingPK implements Serializable;
    
    private static final long ResumeRatingPK.serialVersionUID = 1L;
    
}
