// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.reltecsoft.lookon.domain;

import com.reltecsoft.lookon.domain.SharedNotesPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SharedNotesPK_Roo_Configurable {
    
    declare @type: SharedNotesPK: @Configurable;
    
}
